QuotesLand/force-app/main/default/objects/Picture__c/Picture__c.object-meta.xml
<CustomObject>
    <label>Picture</label>
    <nameField>
        <label>Picture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pictures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QuotesLand/force-app/main/default/objects/Picture__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>13</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Picture__c/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>url</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Picture__c/fields/Votes__c.field-meta.xml
<CustomField>
    <fullName>Votes__c</fullName>
    <label>Votes</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Poster__c/Poster__c.object-meta.xml
<CustomObject>
    <label>Poster</label>
    <nameField>
        <label>Poster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QuotesLand/force-app/main/default/objects/Poster__c/fields/Left_Margin__c.field-meta.xml
<CustomField>
    <fullName>Left_Margin__c</fullName>
    <label>Left Margin</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Poster__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <description>Background image for the poster</description>
    <label>Picture</label>
    <referenceTo>Picture__c</referenceTo>
    <relationshipLabel>Posters</relationshipLabel>
    <relationshipName>Posters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Poster__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <description>Text on the poster</description>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Posters</relationshipLabel>
    <relationshipName>Posters</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Poster__c/fields/Word_Color__c.field-meta.xml
<CustomField>
    <fullName>Word_Color__c</fullName>
    <label>Word Color</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Poster__c/fields/Word_Height__c.field-meta.xml
<CustomField>
    <fullName>Word_Height__c</fullName>
    <description>Determines placement of text on the poster</description>
    <label>Word Height</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Poster__c/fields/Word_Width__c.field-meta.xml
<CustomField>
    <fullName>Word_Width__c</fullName>
    <label>Word Width</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <label>Quotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QuotesLand/force-app/main/default/objects/Quotation__c/fields/Quote_Text__c.field-meta.xml
<CustomField>
    <fullName>Quote_Text__c</fullName>
    <label>Quote Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

QuotesLand/force-app/main/default/objects/Quotation__c/fields/Search_Category__c.field-meta.xml
<CustomField>
    <fullName>Search_Category__c</fullName>
    <label>Search Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Author</fullName>
            </value>
            <value>
                <fullName>Tag</fullName>
            </value>
            <value>
                <fullName>Title</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

QuotesLand/force-app/main/default/classes/posterDatabase.cls
public class posterDatabase {
    public static Poster__c savePoster(Picture__c pic, Quotation__c quote, String imageSearch, String imageUrl, String quoteSearch,
                                 String quoteAuthor, String quoteCategory, String quoteText, Integer posterTextHeight, Integer posterTextWidth,
                                 Integer posterLeftMargin, String posterTextColor){
        System.debug('Will save poster');
        if(pic == null){
            pic = new Picture__c(Keyword__c = imageSearch, Rating__c = 1, Votes__c = 0, url__c = imageUrl);
            insert pic;
        }
        if(quote == null){
            quote = new Quotation__c(Keyword__c = quoteSearch, Rating__c = 1, Votes__c = 0, Author__c = quoteAuthor, Search_Category__c = quoteCategory, Quote_Text__c = quoteText);
            insert quote;
        }
        Poster__c poster = new Poster__c(Word_Height__c = posterTextHeight, Word_Width__c = posterTextWidth, Word_Color__c = posterTextColor,
                                        Left_Margin__c = posterLeftMargin, Quotation__c = quote.Id, Picture__c = pic.Id);
        insert poster;
        return poster;
    }
    @AuraEnabled
    public static void orderPoster(String Quantity, Poster__c posterId){
        User theUser = [SELECT Id,Alias,Email FROM User WHERE Id = :userInfo.getUserId() LIMIT 1];
        Contact buyer = [SELECT Id,firstName,lastName,email FROM Contact WHERE email = :theUser.Email LIMIT 1];
        System.debug('Will order' + Quantity + ' ' + posterId.Id + ' posters for user ' + buyer.firstName + ' ' + buyer.lastName + '('
                    + buyer.email + ')');
        Order posterOrder = new Order();//(ContractId = '8004W000004rgzsQAA');
        posterOrder.Contact__c = buyer.Id;
        insert posterOrder;
        OrderItem oi = new OrderItem();
        oi.Poster__c = posterId.Id;
        insert oi;
    }
    
}